port: 7890
rtc:
  tcp_port: 7891
  port_range_start: 50200
  port_range_end: 50300
  use_external_ip: false
keys:
  guestrix_key_local_testing_only_not_for_production: guestrix_secret_local_testing_only_not_for_production
logging:
  level: info
